config/routes.rb
Rails.application.routes.draw do
  # don't load User model when building docker image
  unless ARGV.first =~ /^dad:setup(:.+)?/
    devise_for :users, controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
      sessions: 'users/sessions'
    }

    get  'users/two_factor_authentication', to: 'users/two_factor_authentication#show', as: :users_two_factor_authentication
    post 'users/two_factor_authentication', to: 'users/two_factor_authentication#verify'

    get    'users/two_factor_setup', to: 'users/two_factor_setup#show', as: :users_two_factor_setup
    post   'users/two_factor_setup', to: 'users/two_factor_setup#enable'
    delete 'users/two_factor_setup', to: 'users/two_factor_setup#disable'
  end

  resources :bookmarks

  resources :calendars do
    member do
      get  'get_gadget'
    end
  end

  resources :feeds do
    collection do
      post 'get_feed_title'
    end
  end

  resources :preferences, only: ['index', 'create', 'update']

  resources :todos do
    collection do
      post 'delete'
    end
  end
  
  resources :welcome, only: [] do
    collection do
      post 'save_state'
    end
  end

  root to: 'welcome#index'
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  include Crud::ByUser

  belongs_to :user
  acts_as_tree order: 'title'

  scope :folders, -> { where(url: nil) }
  scope :files, -> { where.not(url: nil) }

  validates :title, presence: true
  validate :url_validation
  validate :validate_nesting_depth

  def folder?
    url.nil? || url.blank?
  end

  def file?
    url.present?
  end

  def destroy_logically!
    update!(deleted: true)
  end

  private

  def url_validation
    if folder?
      # フォルダの場合はurlがnilまたは空文字列でなければならない
      if url.present?
        errors.add(:url, 'must be blank for folders')
      end
    else
      # ファイルの場合はurlが必須
      if url.blank?
        errors.add(:url, "can't be blank for files")
      end
    end
  end

  def validate_nesting_depth
    # フォルダはルートレベルでなければならない（parent_idはnil）
    if folder? && parent_id.present?
      errors.add(:parent_id, "folders must be at root level")
      return
    end

    return unless parent_id.present?

    # 自分自身を親に設定することはできない
    if parent_id == id
      errors.add(:parent_id, "can't be set to itself")
      return
    end
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :preload_bookmark, only: ['show', 'edit', 'update', 'destroy']

  def index
    @parent_id = params[:parent_id]
    @parent = @parent_id.present? ? Bookmark.find_by(id: @parent_id, user_id: current_user.id) : nil

    # フォルダを先に、その後ブックマークをタイトル順で表示
    @bookmarks = Bookmark.where(user_id: current_user.id, parent_id: @parent_id, deleted: false).order(Arel.sql('url IS NULL DESC'), :title)

  end

  def show
  end

  def new
    @bookmark = Bookmark.new
    @parent_id = params[:parent_id]
    @bookmark.parent_id = @parent_id if @parent_id.present?
    # 新規作成時はすべてのフォルダを利用可能
    @available_folders = Bookmark.where(user_id: current_user.id, deleted: false).folders.order(:title)
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    
    @bookmark.transaction do
      @bookmark.save!
    end
    
    redirect_to action: 'index', parent_id: @bookmark.parent_id
  end

  def edit
    # 編集時に循環参照を防ぐため、利用可能なフォルダリストを準備
    @available_folders = Bookmark.where(user_id: current_user.id, deleted: false)
                                  .folders
                                  .where.not(id: @bookmark.id)
                                  .order(:title)
  end
  
  def update
    @bookmark.attributes = bookmark_params
    
    @bookmark.transaction do
      @bookmark.save!
    end
    
    redirect_to action: 'index', parent_id: @bookmark.parent_id
  end

  def destroy
    parent_id = @bookmark.parent_id
    
    @bookmark.transaction do
      @bookmark.destroy_logically!
    end
    
    redirect_to action: 'index', parent_id: parent_id
  end

  private

  def preload_bookmark
    @bookmark = Bookmark.find(params[:id])

    unless @bookmark.readable_by?(current_user)
      head :not_found and return
    end
  end

  def bookmark_params
    ret = params.require(:bookmark).permit(:title, :url, :parent_id)
    
    # urlが空文字列の場合はnilに変換（フォルダの場合）
    ret[:url] = nil if ret[:url].blank?

    case action_name
    when 'create'
      ret = ret.merge(user_id: current_user.id)
    end
    
    ret
  end
end

app/views/bookmarks/_form.html.erb
<%= form_for @bookmark do |f| %>
  <table>
    <tr>
      <th><%= f.label :title %></th>
      <td><%= f.text_field :title %></td>
    </tr>
    <tr>
      <th><%= f.label :url %></th>
      <td>
        <%= f.text_field :url, placeholder: 'URL（フォルダの場合は空欄）' %>
        <small>URLを空欄にするとフォルダとして作成されます</small>
      </td>
    </tr>
    <tr>
      <th><%= f.label :parent_id, '親フォルダ' %></th>
      <td>
        <%= f.select :parent_id, 
            options_for_select(
              [['なし（ルート）', nil]] + 
              (@available_folders || Bookmark.where(user_id: current_user.id, deleted: false).folders.order(:title))
                      .map { |f| [f.title, f.id] },
              @bookmark.parent_id
            ),
            {},
            { id: 'bookmark_parent_id' }
        %>
      </td>
    </tr>
  </table>
  <%= f.submit %>
<% end %>

app/views/bookmarks/edit.html.erb
<div class="actions">
  <%= link_to '一覧', bookmarks_path %>
</div>

<%= render 'form' %>

app/views/bookmarks/index.html.erb
<nav class="breadcrumbs" aria-label="パンくずリスト">
  <ol class="breadcrumbs-list">
    <li class="breadcrumbs-item">
      <%= link_to 'ルート', bookmarks_path, class: 'breadcrumbs-link' %>
      <% unless @parent %>
        <span class="breadcrumbs-item-actions">
          <%= link_to new_bookmark_path(parent_id: nil), class: 'breadcrumbs-create-folder', title: 'フォルダを作成' do %>
            <span class="breadcrumbs-icon">📁</span><span class="breadcrumbs-label">フォルダ</span>
          <% end %>
        </span>
      <% end %>
    </li>
    <% if @parent %>
      <li class="breadcrumbs-item breadcrumbs-current">
        <%= @parent.title %>
      </li>
    <% end %>
    <li class="breadcrumbs-item breadcrumbs-actions">
      <span class="breadcrumbs-item-actions">
        <%= link_to new_bookmark_path(parent_id: @parent_id), class: 'breadcrumbs-create-bookmark', title: 'ブックマークを追加' do %>
          <span class="breadcrumbs-icon">🔖</span><span class="breadcrumbs-label">ブックマーク</span>
        <% end %>
      </span>
    </li>
  </ol>
</nav>

<table class="bookmarks-table">
  <thead>
    <tr>
      <th><%= Bookmark.human_attribute_name :title %></th>
      <th>URL</th>
      <th colspan="2">操作</th>
    </tr>
  </thead>
  <tbody>
    <% @bookmarks.each do |b| %>
      <tr class="<%= 'folder' if b.folder? %>">
        <td>
          <% if b.folder? %>
            <%= link_to b.title, bookmarks_path(parent_id: b.id), class: 'folder-link' %>
          <% else %>
            <%= link_to b.title, b.url, target: '_blank' %>
          <% end %>
        </td>
        <td>
          <% unless b.folder? %>
            <%= b.url %>
          <% end %>
        </td>
        <td><%= link_to '編集', edit_bookmark_path(b) %></td>
        <td>
          <%= link_to '削除', bookmark_path(b), method: 'delete', data: { confirm: t('messages.confirm_delete', name: b.title) } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bookmarks/show.html.erb
<div class="actions">
  <%= link_to '一覧', bookmarks_path(parent_id: @bookmark.parent_id) %>
  <%= link_to '編集', edit_bookmark_path(@bookmark) %>
</div>

<table>
  <tr>
    <th><%= Bookmark.human_attribute_name :title %></th>
    <td><%= @bookmark.title %></td>
  </tr>
  <% unless @bookmark.folder? %>
    <tr>
      <th><%= Bookmark.human_attribute_name :url %></th>
      <td><%= @bookmark.url %></td>
    </tr>
  <% end %>
  <% if @bookmark.parent %>
    <tr>
      <th>親フォルダ</th>
      <td><%= link_to @bookmark.parent.title, bookmarks_path(parent_id: @bookmark.parent.id) %></td>
    </tr>
  <% end %>
</table>