config/routes.rb
Rails.application.routes.draw do
  # don't load User model when building docker image
  unless ARGV.first =~ /^dad:setup(:.+)?/
    devise_for :users, controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
      sessions: 'users/sessions'
    }

    get  'users/two_factor_authentication', to: 'users/two_factor_authentication#show', as: :users_two_factor_authentication
    post 'users/two_factor_authentication', to: 'users/two_factor_authentication#verify'

    get    'users/two_factor_setup', to: 'users/two_factor_setup#show', as: :users_two_factor_setup
    post   'users/two_factor_setup', to: 'users/two_factor_setup#enable'
    delete 'users/two_factor_setup', to: 'users/two_factor_setup#disable'
  end

  resources :bookmarks

  resources :calendars do
    member do
      get  'get_gadget'
    end
  end

  resources :feeds do
    collection do
      post 'get_feed_title'
    end
  end

  resources :preferences, only: ['index', 'create', 'update']

  resources :todos do
    collection do
      post 'delete'
    end
  end
  
  resources :welcome, only: [] do
    collection do
      post 'save_state'
    end
  end

  root to: 'welcome#index'
end

app/models/feed.rb
require 'daddy/http_client'

module FeedConst
  DEFAULT_DISPLAY_COUNT = 5
end

class Feed < ApplicationRecord
  include FeedConst
  include Crud::ByUser

  before_save :set_display_count

  def feed
    if @feed.nil?
      begin
        @feed ||= retrieve_feed
      rescue => e
        Rails.logger.error e.message
        @feed = false
      end
    end
    
    @feed
  end

  def status
    return :success if feed?
    return feed if feed.is_a?(Integer)
    :internal_server_error
  end

  def feed?
    return true if feed.is_a?(Feedjira::Parser::RSS)
    return true if feed.is_a?(Feedjira::Parser::Atom)
    return true if feed.is_a?(Feedjira::Parser::RSSFeedBurner)
    Rails.logger.info "unknown class for feed: #{feed.class.name}"
    false
  end

  def gadget_id
    "feed_#{self.id}"
  end

  def url
    feed? ? feed.url : nil
  end

  def entries
    if feed?
      feed.entries.slice(0, self.display_count)
    else
      []
    end
  end

  private

  def set_display_count
    self.display_count = DEFAULT_DISPLAY_COUNT if self.display_count.to_i == 0
  end

  def retrieve_feed
    client = Daddy::HttpClient.new(base_url, follow_redirects: true)
    xml = client.get(request_path, request_params)

    Feedjira.parse(xml)
  end

  def base_url
    split = self.feed_url.split('/')
    url = split[0] + '//' + split[2]
  end

  def request_path
    split = self.feed_url.split('/')
    split = ('/' + split[3..-1].join('/')).split('?')
    split[0]
  end

  def request_params
    split = self.feed_url.split('/')
    split = ('/' + split[3..-1].join('/')).split('?')

    ret = {}

    split[1].split('&').each do |query|
      key_value = query.split('=')
      ret[key_value[0]] = key_value[1]
    end if split[1]
    
    ret
  end

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :preload_feed, only: ['show', 'edit', 'update', 'destroy']

  def index
    @feeds = Feed.where(user_id: current_user.id).not_deleted
  end

  def show
    if @feed.feed?
      render layout: !request.xhr?
    else
      render plain: @feed.status, status: @feed.status
    end
  end

  def new
    @feed = Feed.new
  end

  def create
    @feed = Feed.new(feed_params)

    @feed.transaction do
      @feed.save!
    end

    redirect_to action: 'index'
  end

  def edit
  end

  def update
    @feed.attributes = feed_params

    @feed.transaction do
      @feed.save!
    end

    redirect_to action: 'index'
  end

  def destroy
    @feed.transaction do
      @feed.destroy_logically!
    end

    redirect_to action: 'index'
  end

  def get_feed_title
    @feed = Feed.new(feed_params)
    if @feed.feed?
      render plain: @feed.feed.title
    else
      head :ok
    end
  end

  private

  def preload_feed
    @feed = Feed.find(params[:id])

    unless @feed.readable_by?(current_user)
      head :not_found and return
    end
  end

  def feed_params
    ret = params.require(:feed).permit(:title, :feed_url, :display_count)

    ret.merge!(user_id: current_user.id)

    ret
  end

end

app/views/feeds/_form.html.erb
<%= form_for @feed do |f| %>
  <table>
    <tr>
      <th><%= f.label :feed_url %></th>
      <td><%= f.text_field :feed_url, class: 'feed_url' %></td>
    </tr>
    <tr>
      <th><%= f.label :title %></th>
      <td>
        <%= f.text_field :title %>
        <%= f.button 'フィードから取得', onclick: 'feeds.get_feed_title(this); return false;', 'data-url': url_for(action: 'get_feed_title') %>
      </td>
    </tr>
    <tr>
      <th><%= f.label :display_count %></th>
      <td><%= f.number_field :display_count, class: 'display_count' %></td>
    </tr>
    <tr>
      <td colspan="2"><%= f.submit %></td>
    </tr>
  </table>
<% end %>

app/views/feeds/index.html.erb
<div class="actions">
  <%= link_to '追加', new_feed_path %>
</div>

<% unless @feeds.present? %>
  <div>1件も登録されていません。</div>
<% else %>
  <table class="feeds">
    <tr>
      <th>サイト名</th>
      <th>表示件数</th>
      <th>フィードURL</th>
      <th colspan="2"></th>
    </tr>
    
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.title %></td>
        <td class="center"><%= feed.display_count %></td>
        <td><div class="feed_url"><%= feed.feed_url %></div></td>
        <td><%= link_to '編集', edit_feed_path(feed) %></td>
        <td><%= link_to '削除', feed_path(feed), method: 'delete', confirm: t('messages.confirm_delete', name: feed.title) %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/feeds/new.html.erb
<div class="actions">
  <%= link_to '一覧へ', feeds_path %>
</div>

<%= render 'form' %>