config/routes.rb
Rails.application.routes.draw do
  # don't load User model when building docker image
  unless ARGV.first =~ /^dad:setup(:.+)?/
    devise_for :users, controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
      sessions: 'users/sessions'
    }

    get  'users/two_factor_authentication', to: 'users/two_factor_authentication#show', as: :users_two_factor_authentication
    post 'users/two_factor_authentication', to: 'users/two_factor_authentication#verify'

    get    'users/two_factor_setup', to: 'users/two_factor_setup#show', as: :users_two_factor_setup
    post   'users/two_factor_setup', to: 'users/two_factor_setup#enable'
    delete 'users/two_factor_setup', to: 'users/two_factor_setup#disable'
  end

  resources :bookmarks

  resources :calendars do
    member do
      get  'get_gadget'
    end
  end

  resources :feeds do
    collection do
      post 'get_feed_title'
    end
  end

  resources :preferences, only: ['index', 'create', 'update']

  resources :todos do
    collection do
      post 'delete'
    end
  end
  
  resources :welcome, only: [] do
    collection do
      post 'save_state'
    end
  end

  root to: 'welcome#index'
end

app/models/todo.rb
module TodoConst
  PRIORITIES = {
    PRIORITY_HIGH = 1 => '高',
    PRIORITY_NORMAL = 2 => '中',
    PRIORITY_LOW = 3 => '低',
  }
end

class Todo < ActiveRecord::Base
  include TodoConst
  include Crud::ByUser

  belongs_to :user

  def priority_name
    PRIORITIES[self.priority]
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :preload_todo, only: ['edit', 'update', 'destroy']
  
  def index
    @todos = Todo.where(user_id: current_user).not_deleted.order(:title)
  end

  def new
    @todo = Todo.new(user: current_user, priority: current_user.preference.default_priority)
    render layout: !request.xhr?
  end

  def create
    @todo = Todo.new(todo_params)
    
    @todo.transaction do
      @todo.save!
    end

    render partial: 'todo', locals: { todo: @todo }
  end

  def edit
    render layout: !request.xhr?
  end

  def update
    @todo.attributes = todo_params

    @todo.transaction do
      @todo.save!
    end

    render partial: 'todo', locals: { todo: @todo }
  end

  def destroy
    @todo.transaction do
      @todo.destroy_logically!
    end
    
    redirect_to action: 'index'
  end

  def delete
    if params[:todo_id].present?
      Todo.transaction do
        params[:todo_id].each do |id|
          @todo = Todo.find(id)
          head :not_found and return unless @todo.deletable_by?(current_user)
          @todo.destroy_logically!
        end
      end
    end

    head :ok
  end

  private

  def preload_todo
    @todo = Todo.find(params[:id])

    unless @todo.readable_by?(current_user)
      head :not_found and return
    end
  end

  def todo_params
    ret = params.require(:todo).permit(:title, :priority)
    
    case action_name
    when 'create'
      ret = ret.merge(user_id: current_user.id)
    end
    
    ret
  end

end

app/views/todos/_actions.html.erb
<li class="todo_actions" data-authenticity_token="<%= form_authenticity_token %>">
  <span style="float: left;"><%= link_to '完了', delete_todos_path, onclick: 'todos.delete_todos(this); return false;' %></span>
  <span style="float: right;"><%= link_to '新しいタスク',  new_todo_path, onclick: 'todos.new_todo(this); return false;' %></span>
</li>

app/views/todos/_form.html.erb
<%= form_with model: @todo, html: {class: 'todo'} do |f| %>
  <table>
    <tr>
      <td><%= f.select :priority, Todo::PRIORITIES.invert %></td>
      <td><%= f.text_field :title %></td>
      <td>
        <% if @todo.new_record? %>
          <%= f.submit '登録', onclick: 'todos.create_todo(this); return false;' %>
        <% else %>
          <%= f.submit '更新', onclick: 'todos.update_todo(this); return false;' %>
        <% end %>
      </td>
    </tr>
  </table>
<% end %>

app/views/todos/_todo.html.erb
<li data-id="<%= todo.id %>" data-url="<%= edit_todo_path(todo) %>">
  <span class="<%= "priority_#{todo.priority}" %> center"><%= todo.priority_name %></span>
  <span><%= todo.title %></span>
</li>

app/views/todos/edit.html.erb
<%= render 'form' %>

app/views/todos/index.html.erb
<table>
  <tr>
    <th><%= Todo.human_attribute_name :priority %></th>
    <th><%= Todo.human_attribute_name :title %></th>
    <th></th>
  </tr>
  
  <% @todos.each do |t| %>
    <tr>
      <td><%= t.title %></td>
      <td>
        <%= link_to '削除', todo_path(t), method: 'delete', confirm: t('messages.confirm_delete', name: t.title) %>
      </td>
    </tr>
  <% end %>
</table>

app/views/todos/new.html.erb
<%= render 'form' %>