config/routes.rb
Rails.application.routes.draw do
  # don't load User model when building docker image
  unless ARGV.first =~ /^dad:setup(:.+)?/
    devise_for :users, controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
      sessions: 'users/sessions'
    }

    get  'users/two_factor_authentication', to: 'users/two_factor_authentication#show', as: :users_two_factor_authentication
    post 'users/two_factor_authentication', to: 'users/two_factor_authentication#verify'

    get    'users/two_factor_setup', to: 'users/two_factor_setup#show', as: :users_two_factor_setup
    post   'users/two_factor_setup', to: 'users/two_factor_setup#enable'
    delete 'users/two_factor_setup', to: 'users/two_factor_setup#disable'
  end

  resources :bookmarks

  resources :calendars do
    member do
      get  'get_gadget'
    end
  end

  resources :feeds do
    collection do
      post 'get_feed_title'
    end
  end

  resources :preferences, only: ['index', 'create', 'update']

  resources :todos do
    collection do
      post 'delete'
    end
  end
  
  resources :welcome, only: [] do
    collection do
      post 'save_state'
    end
  end

  root to: 'welcome#index'
end

app/views/common/_menu.html.erb
<div class="header">
  <script>
    function toggle_menu(trigger, menu) {
      menu.toggleClass('hidden');
      if (menu.is(':visible')) {
        menu.css('min-width', trigger.outerWidth() - 10);
        menu.position({my: 'right top', at: 'right bottom', of: trigger});
      }
    }

    $(document).ready(function() {
      var header = $('.header').first();
      var email = header.find('.email').first();
      var menu = header.find('.menu').first();

      email.click(function() {
        toggle_menu(email, menu);
      });

      menu.delegate('a', 'click', function() {
        if ($(this).attr('target') == '_blank') {
          toggle_menu(email, menu);
        }
      });
      
      $('html').click(function(e) {
        if ($(e.target).closest('.email').length == 0) {
          menu.addClass('hidden');
        }
      });
    });
  </script>
  <div>
    <ul class="navigation">
      <li><%= link_to 'Home', root_path %></li>
      <li class="email">
        <a href="#"><%= current_user.display_name %><span style="font-size: 0.8em;"> ▼</span></a>
        <div class="menu hidden">
          <div><%= link_to '設定', preferences_path %></div>
          <div><%= link_to 'ブックマーク', bookmarks_path %></div>
          <div><%= link_to 'タスク', todos_path %></div>
          <div><%= link_to 'カレンダー', calendars_path %></div>
          <div><%= link_to 'フィード', feeds_path %></div>
          <div><%= link_to 'ログアウト', destroy_user_session_path, method: 'delete' %></div>
        </div>
      </li>
    </ul>
  </div>
</div>